Adding our new recipe to the image so we can see it on the target.
The objective is to $ bitbake core-image-minimal  and have our added
package in the target.

This has several failures, due to our non standard folder hierarchy:

At first, there is a run time dependency that is not satisfied because RPROVIDE is not resolved:
ERROR: Nothing RPROVIDES 'blablabla' (but /home/ubuntu/Tutorials/poky-zeus-22.0.2/meta/recipes-core/images/core-image-minimal.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'blablabla' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['blablabla']
ERROR: Required build target 'core-image-minimal' has no buildable providers.
Missing or unbuildable dependency chain was: ['core-image-minimal', 'blablabla']

Then, we give an arbitrary RPROVIDES, but it will not pass QA:

ERROR: /home/ubuntu/prep/build-0/meta-pscg/recipes-demo/corona-opinions/corona_opinions_1.0.bb: QA Issue: /home/ubuntu/prep/build-0/meta-pscg/recipes-demo/corona-opinions/corona_opinions_1.0.bb: Variable RPROVIDES is set as not being package specific, please fix this. [pkgvarcheck]
ERROR: /home/ubuntu/prep/build-0/meta-pscg/recipes-demo/corona-opinions/corona_opinions_1.0.bb: Fatal QA errors found, failing task.
ERROR: Failed to parse recipe: /home/ubuntu/prep/build-0/meta-pscg/recipes-demo/corona-opinions/corona_opinions_1.0.bb

We can workaround this too, but the easiest solution (And the right
one!) is to make things right. We will do it on the next commit - in a
different branch.